# Generated by Django 6.0.5 on 2026-05-27 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['organization', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('natural_gas', 'Natural Gas'), ('kerosene', 'Kerosene'), ('jet_fuel', 'Jet Fuel'), ('grid_electricity', 'Grid Electricity'), ('flight_short', 'Flight < 500 km'), ('flight_medium', 'Flight 500-1500 km'), ('flight_long', 'Flight > 1500 km'), ('hotel', 'Hotel Stay'), ('car_rental', 'Car Rental'), ('bus', 'Bus Travel'), ('rail', 'Rail Travel')], max_length=50)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('region', models.CharField(choices=[('GLOBAL', 'Global Average'), ('US', 'United States'), ('EU', 'European Union'), ('UK', 'United Kingdom')], default='GLOBAL', max_length=20)),
                ('factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('factor_unit', models.CharField(help_text='e.g. tonnes_CO2e_per_kWh, kg_CO2e_per_km', max_length=100)),
                ('source', models.CharField(help_text='e.g. DEFRA 2024, EPA eGRID 2023', max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'region', '-valid_from'],
                'indexes': [models.Index(fields=['category', 'region', 'valid_from'], name='ingestion_e_categor_0f964f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('importing', 'Importing'), ('staged', 'Staged for Review'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], default='importing', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('batch_created', 'Batch Created'), ('record_ingested', 'Record Ingested'), ('record_approved', 'Record Approved'), ('record_rejected', 'Record Rejected'), ('record_flagged', 'Record Flagged'), ('record_locked', 'Record Locked'), ('record_unlocked', 'Record Unlocked'), ('batch_locked', 'Batch Locked'), ('batch_approved', 'Batch Approved'), ('record_edited', 'Record Edited')], max_length=50)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('record_type', models.CharField(blank=True, help_text='Model name', max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('data_source', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50)),
                ('raw_quantity', models.CharField(blank=True, max_length=255)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('raw_date', models.CharField(blank=True, max_length=255)),
                ('raw_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('passed', 'Passed Validation'), ('failed', 'Failed Validation'), ('suspicious', 'Suspicious')], default='staged', max_length=20)),
                ('failure_reasons', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Purchased Energy'), (3, 'Scope 3 - Value Chain')])),
                ('category', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('natural_gas', 'Natural Gas'), ('kerosene', 'Kerosene'), ('jet_fuel', 'Jet Fuel'), ('grid_electricity', 'Grid Electricity'), ('flight_short', 'Flight < 500 km'), ('flight_medium', 'Flight 500-1500 km'), ('flight_long', 'Flight > 1500 km'), ('hotel', 'Hotel Stay'), ('car_rental', 'Car Rental'), ('bus', 'Bus Travel'), ('rail', 'Rail Travel'), ('procurement', 'General Procurement')], max_length=50)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50)),
                ('activity_date', models.DateField()),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=50)),
                ('co2e', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('co2e_unit', models.CharField(default='tonnes_CO2e', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_values', models.JSONField(blank=True, default=dict, help_text='Snapshot of raw values for diff view')),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('locked', 'Locked for Audit')], default='needs_review', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.organization')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='ingestion.sourcerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('category', models.CharField(blank=True, help_text='Optional: restrict to emission category', max_length=50)),
            ],
            options={
                'ordering': ['from_unit'],
                'unique_together': {('from_unit', 'to_unit', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['batch', 'status'], name='ingestion_s_batch_i_afb22d_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['organization', 'status'], name='ingestion_n_organiz_e13756_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['batch', 'status'], name='ingestion_n_batch_i_82adfe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['scope', 'category'], name='ingestion_n_scope_70500c_idx'),
        ),
    ]
